name: Reset Environment for New Participant

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run reset script
        run: |
          chmod +x .github/reset.sh
          ./.github/reset.sh
